Repository Workout-Study/WorkoutStudy_Android, pull requests merged in 2024-08, with the labels that each got.

#131 내 정보 화면 및 정보 변경화면 데이터 수정 #2
  app/src/main/java/com/fitmate/fitmate/data/model/dto/LoginDto.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/category/CategorySelectFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/ProfileFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/fragment_category_select.xml
  app/src/main/res/layout/fragment_nickname.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/navigation/nav_main_graph.xml
Labels: UI, feat

#134 Feat add point fragment function complete
  app/src/main/java/com/fitmate/fitmate/presentation/ui/point/PointFragment.kt
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/text_list_item.xml
  app/src/main/res/navigation/nav_main_graph.xml
  app/src/main/res/values/strings.xml
Labels: feat

#136 Update style & Function #100
  app/src/main/java/com/fitmate/fitmate/data/model/dto/GroupDto.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/FitMateListAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/ProfileFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable-hdpi/left_speech_svg.9.png
  app/src/main/res/drawable-hdpi/right_speech.9.png
  app/src/main/res/drawable-mdpi/left_speech_svg.9.png
  app/src/main/res/drawable-mdpi/right_speech.9.png
  app/src/main/res/drawable-xhdpi/left_speech_svg.9.png
  app/src/main/res/drawable-xhdpi/right_speech.9.png
  app/src/main/res/drawable-xxhdpi/left_speech_svg.9.png
  app/src/main/res/drawable-xxhdpi/right_speech.9.png
  app/src/main/res/drawable-xxxhdpi/left_speech_svg.9.png
  app/src/main/res/drawable-xxxhdpi/right_speech.9.png
  app/src/main/res/drawable/ic_baseline_alarm_new.png
  app/src/main/res/drawable/ic_baseline_png_onboard_1.png
  app/src/main/res/drawable/ic_baseline_storage_new.png
  app/src/main/res/layout/fragment_chatting.xml
  app/src/main/res/layout/fragment_on_boarding_fifth.xml
  app/src/main/res/layout/fragment_on_boarding_fourth.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_permission.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/layout/item_chatting_chat.xml
  app/src/main/res/layout/item_chatting_fit_mate.xml
  app/src/main/res/layout/item_permission.xml
  app/src/main/res/layout/test.xml
  app/src/main/res/values/strings.xml
Labels: UI, feat

#139 Get FitMate List 호출 시점 변경 #125
  app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt
Labels: feat

#140 그룹 내 fitMate 정보 호출 시점 변경 #125
  app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt
Labels: feat

#146 Fix Splash Screen on Under S Version # 62
  app/src/main/java/com/fitmate/fitmate/MainActivity.kt
  app/src/main/res/drawable/ic_launcher_splash.xml
  app/src/main/res/drawable/splash.xml
  app/src/main/res/values/themes.xml
Labels: UI
