Repository Workout-Study/WorkoutStudy_Android, pull requests merged in 2024-03, with the labels that each got.

#4 온보딩 화면 UI작성 완료 #1
  app/build.gradle.kts
  app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnboardingContainerFragment.kt
  app/src/main/res/layout/fragment_onboarding_container.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/raw/first_onboarding.json
  app/src/main/res/raw/second_onboarding.json
  app/src/main/res/raw/third_onboarding.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Libraries.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: UI

#13 Group 상세 화면 구현 #9
  app/src/main/res/layout/fragment_group_join.xml
  app/src/main/res/values/strings.xml
Labels: UI, Feat

#18 그룹 만들기 화면 UI 제작 #17
  app/src/main/res/drawable/bg_rounded_group_1.xml
  app/src/main/res/drawable/bg_rounded_group_2.xml
  app/src/main/res/drawable/bg_rounded_group_3.xml
  app/src/main/res/drawable/bg_rounded_group_4.xml
  app/src/main/res/drawable/bg_rounded_group_5.xml
  app/src/main/res/layout/fragment_make_group.xml
  app/src/main/res/values/strings.xml
Labels: UI

#20 그룹 내 피트오프 열람 화면 UI 구현 #19
  app/src/main/res/drawable/bg_rounded_fit_off.xml
  app/src/main/res/layout/fragment_group_fit_off.xml
  app/src/main/res/layout/item_fit_off.xml
  app/src/main/res/values/strings.xml
Labels: UI

#23 그룹 내 피트오프 신청 화면 UI 구현 #21
  app/src/main/res/drawable/bg_rounded_group_6.xml
  app/src/main/res/layout/fragment_make_fit_off.xml
  app/src/main/res/values/strings.xml
Labels: UI

#25 바텀 네비게이션 화면 전환 구현 #24
  app/build.gradle.kts
  app/src/main/java/com/fitmate/fitmate/MainActivity.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeCategoryFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeMainFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/login/LoginFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/myfit/MyFitFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/mygroup/MakeGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/mygroup/MyGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingFirstFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingPermissionFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingSecondFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingThirdFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/userinfo/LisenceFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/navigation/nav_main_graph.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Libraries.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: UI, feat

#27 유저 정보화면 UI 구현 #2
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/values/themes.xml
Labels: UI

#29 그룹 내 운동 현황 화면 UI 구현 #28
  app/src/main/res/layout/fragment_myfit.xml
  app/src/main/res/layout/fragment_progress.xml
  app/src/main/res/layout/item_myfit_progress.xml
  app/src/main/res/layout/item_progress.xml
  app/src/main/res/values/strings.xml
Labels: UI

#32 채팅 화면 내부 그룹 투표 현황 화면 UI 구현 #31
  app/src/main/res/layout/fragment_group_vote.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/item_progress.xml
  app/src/main/res/layout/item_vote.xml
  app/src/main/res/values/strings.xml
Labels: UI

#40 홈 화면 연결 이식 작업
  app/src/main/java/com/fitmate/fitmate/MainActivity.kt
  app/src/main/java/com/fitmate/fitmate/domain/model/CategoryItem.kt
  app/src/main/java/com/fitmate/fitmate/domain/model/VoteItem.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/GroupJoinFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeCategoryFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeMainFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/CategoryViewHolder.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/VoteViewHolder.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/adapter/CarouselAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/adapter/CategoryAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/adapter/VoteAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/CertificateFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitOffFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MyFitGroupProgressViewHolder.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MyFitHistoryViewHolder.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MyFitOffViewHolder.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MyFitGroupProgressAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MyFitHistoryAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MyFitOffAdapter.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnBoardingFirstFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnBoardingPermissionFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnBoardingSecondFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnBoardingThirdFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnboardingContainerFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/LisenceFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeCategoryFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/home/HomeMainFragment.kt
  app/src/main/java/com/fitmate/fitmate/ui/mygroup/MyGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/util/ControlActivityInterface.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_group_join.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_category.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_my_group.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_main_carousel.xml
  app/src/main/res/layout/item_vote.xml
  app/src/main/res/navigation/nav_main_graph.xml
Labels: feat

#42 유저 정보 화면 연결 작업 #24
  app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/LisenceFragment.kt
  app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt
  app/src/main/res/layout/fragment_group_join.xml
  app/src/main/res/layout/fragment_license.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/navigation/nav_main_graph.xml
Labels: UI, feat
